
CREATE  DATABASE Exams;


CREATE TABLE IF NOT EXISTS ROLES (
                                     ROLE_ID INTEGER PRIMARY KEY,
                                     ROLE_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS USERS (
                                     USER_ID SERIAL PRIMARY KEY,
                                     NAME VARCHAR,
                                     EMAIL VARCHAR,
                                     VALIDATED BOOLEAN,
                                     PASSWEORD_HASH VARCHAR,
                                     CREATED TIMESTAMP WITH TIME ZONE,
                                     ROLE_ID INTEGER REFERENCES ROLES(ROLE_ID)
);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (1, 'Administrator') ON CONFLICT DO NOTHING ;
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (2, 'Teacher') ON CONFLICT DO NOTHING ;
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (3, 'Student') ON CONFLICT DO NOTHING ;

/* =============================================================== */


CREATE TABLE IF NOT EXISTS SUBJECTS (
   SUBJECT_ID SERIAL PRIMARY KEY,
   SUBJECT_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS SCHOOL_CLASSES (
    CLASS_ID SERIAL PRIMARY KEY,
    CLASS_GRADE INTEGER,
    CLASS_NAME VARCHAR,
    CLASS_COMMENT VARCHAR
);

CREATE TABLE IF NOT EXISTS EXAMS (
    EXAM_ID SERIAL PRIMARY KEY,
    EXAM_NAME VARCHAR,
    EXAM_COMMENT VARCHAR,
    EXAM_INSTRUCTIONS VARCHAR,
    SUBJECT INTEGER REFERENCES SUBJECTS(SUBJECT_ID),
    CLASS INTEGER REFERENCES SCHOOL_CLASSES(CLASS_ID)
);

CREATE TABLE IF NOT EXISTS EXAM_SECTIONS (
    EXAM_SECTION_ID SERIAL PRIMARY KEY,
    EXAM_ID INTEGER REFERENCES EXAMS(EXAM_ID),
    SECTION_NAME VARCHAR,
    SECTION_COMMENT VARCHAR,
    SECTION_INSTRUCTIONS VARCHAR,
    SECTION_WEIGHT DOUBLE PRECISION
);
